### ISSUE TITLE
401 OAuth token is missing

### ISSUE THREAD

**Issue by crstauf** [daskeyboard/daskeyboard-applet--twitch#2]
No prompt for authorization results in unauthorized access to Twitch API.

`The Twitch service returned an error. Detail: Error: Error when trying to retrieveData: StatusCodeError: 401 - {"error":"Unauthorize","status":401,"message":"OAuth token is missing"}`

<img width="214" alt="Screen Shot 2020-07-09 at 10 12 17 AM" src="https://user-images.githubusercontent.com/4573033/87050777-bc02a300-c1cc-11ea-81e6-52ffd76d4e8e.png">

**Comment by crstauf** [comment]
@fabiendv Could this be fixed somehow?

**Comment by fabiendv** [comment]
Hi @crstauf,
I am not working at DasKeyboard anymore.
However, I will take a look even if I am sure the team is on it.
Thanks,

**Comment by crstauf** [comment]
Thank you, @fabiendv.

**Comment by fabiendv** [comment]
Applet has been fixed.

Enjoy!
